### ISSUE TITLE
UnhandledPromiseRejectionWarning with dimmer switches after 2.6.0

### ISSUE THREAD

**Issue by TravelinMax** [Foddy/node-red-contrib-huemagic#138]
**Describe the bug**
After updating to 2.6.0, pressing any dimmer switch button only produces the following error:
```

(node:503) UnhandledPromiseRejectionWarning: ReferenceError: send is not defined
    at EventEmitter.<anonymous> (/opt/node_modules/node-red-contrib-huemagic/huemagic/hue-switch.js:89:6)
    at EventEmitter.emit (events.js:210:5)
    at HueBridge.emitUpdates (/opt/node_modules/node-red-contrib-huemagic/huemagic/hue-bridge-config.js:215:18)
    at /opt/node_modules/node-red-contrib-huemagic/huemagic/hue-bridge-config.js:41:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Flow to Reproduce**
```

[
    {
        "id": "b85be7e2.c3cc7",
        "type": "tab",
        "label": "Bedroom Dimmer Switches",
        "disabled": false,
        "info": ""
    },
    {
        "id": "4fc0d9ec.251bd",
        "type": "hue-switch",
        "z": "b85be7e2.c3cc7",
        "name": "Bedroom switch nightstand",
        "bridge": "9b095f27.81a95",
        "sensorid": "5",
        "skipevents": false,
        "x": 180,
        "y": 160,
        "wires": [
            [
                "ab824b78.aba72"
            ]
        ]
    },
    {
        "id": "ab824b78.aba72",
        "type": "switch",
        "z": "b85be7e2.c3cc7",
        "name": "",
        "property": "payload.name",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "On",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "Dim Up",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "Dim Down",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "Off",
                "vt": "str"
            }
        ],
        "checkall": "false",
        "repair": false,
        "outputs": 4,
        "x": 690,
        "y": 220,
        "wires": [
            [
                "12093564.0d0c43",
                "6c2cd708.d570f"
            ],
            [
                "8a93800d.0eaed",
                "a24bfe89.7527c8"
            ],
            [
                "ead255c4.16932"
            ],
            [
                "6c2cd708.d570f",
                "a24bfe89.7527c8"
            ]
        ]
    },
    {
        "id": "12093564.0d0c43",
        "type": "api-call-service",
        "z": "b85be7e2.c3cc7",
        "name": "Toggle nightstand lamp.",
        "server": "bc583c80.d8d",
        "version": 1,
        "debugenabled": false,
        "service_domain": "switch",
        "service": "toggle",
        "entityId": "switch.nightstand",
        "data": "",
        "dataType": "json",
        "mergecontext": "",
        "output_location": "payload",
        "output_location_type": "msg",
        "mustacheAltTags": false,
        "x": 990,
        "y": 120,
        "wires": [
            []
        ],
        "icon": "node-red-contrib-huemagic/hue-group.png"
    },
    {
        "id": "6c2cd708.d570f",
        "type": "api-call-service",
        "z": "b85be7e2.c3cc7",
        "name": "Turn off overhead light.",
        "server": "bc583c80.d8d",
        "version": 1,
        "debugenabled": false,
        "service_domain": "light",
        "service": "turn_off",
        "entityId": "light.bedroom",
        "data": "",
        "dataType": "json",
        "mergecontext": "",
        "output_location": "payload",
        "output_location_type": "msg",
        "mustacheAltTags": false,
        "x": 990,
        "y": 180,
        "wires": [
            []
        ],
        "icon": "node-red-contrib-huemagic/hue-light.png"
    },
    {
        "id": "8a93800d.0eaed",
        "type": "api-call-service",
        "z": "b85be7e2.c3cc7",
        "name": "Toggle overhead light.",
        "server": "bc583c80.d8d",
        "version": 1,
        "debugenabled": false,
        "service_domain": "light",
        "service": "toggle",
        "entityId": "light.bedroom",
        "data": "",
        "dataType": "json",
        "mergecontext": "",
        "output_location": "payload",
        "output_location_type": "msg",
        "mustacheAltTags": false,
        "x": 980,
        "y": 240,
        "wires": [
            []
        ],
        "icon": "node-red-contrib-huemagic/hue-light.png"
    },
    {
        "id": "a24bfe89.7527c8",
        "type": "api-call-service",
        "z": "b85be7e2.c3cc7",
        "name": "Turn off nightstand lamp.",
        "server": "bc583c80.d8d",
        "version": "1",
        "debugenabled": false,
        "service_domain": "switch",
        "service": "turn_off",
        "entityId": "switch.nightstand",
        "data": "",
        "dataType": "json",
        "mergecontext": "",
        "output_location": "payload",
        "output_location_type": "msg",
        "mustacheAltTags": false,
        "x": 990,
        "y": 300,
        "wires": [
            []
        ],
        "icon": "node-red-contrib-huemagic/hue-group.png"
    },
    {
        "id": "ead255c4.16932",
        "type": "api-call-service",
        "z": "b85be7e2.c3cc7",
        "name": "Toggle bedroom fan.",
        "server": "bc583c80.d8d",
        "version": "1",
        "debugenabled": false,
        "service_domain": "switch",
        "service": "toggle",
        "entityId": "switch.bedroom_fan",
        "data": "",
        "dataType": "json",
        "mergecontext": "",
        "output_location": "payload",
        "output_location_type": "msg",
        "mustacheAltTags": false,
        "x": 980,
        "y": 360,
        "wires": [
            []
        ],
        "icon": "font-awesome/fa-refresh"
    },
    {
        "id": "50e7fa.443ac808",
        "type": "hue-switch",
        "z": "b85be7e2.c3cc7",
        "name": "Bedroom switch wall",
        "bridge": "9b095f27.81a95",
        "sensorid": "7",
        "skipevents": false,
        "x": 150,
        "y": 280,
        "wires": [
            [
                "ab824b78.aba72"
            ]
        ]
    },
    {
        "id": "d5c36a19.0a6438",
        "type": "debug",
        "z": "b85be7e2.c3cc7",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": true,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 690,
        "y": 140,
        "wires": []
    },
    {
        "id": "9b095f27.81a95",
        "type": "hue-bridge",
        "z": "",
        "name": "Philips hue",
        "bridge": "192.168.30.6",
        "key": "<censored>",
        "interval": "500",
        "disableupdates": false
    },
    {
        "id": "bc583c80.d8d",
        "type": "server",
        "z": "",
        "name": "Home Assistant",
        "legacy": false,
        "hassio": true,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open"
    }
]

```

**Expected behavior**
I expect the dimmer switch node to send it’s payload to the next node and not error.

**Please complete the following information:**
 - NodeRED version: 1.0.3
 - NodeJS version: 12.14.0
 - Device running NodeRED: Fedora 31 (Server Edition)  (amd64 / qemux86-64) (Hassio addon)

**Additional context**
I re-paired with the Hue bridge and that didn’t fix it. Maybe something else I should try?

**Comment by Foddy** [comment]
Fixed with v2.6.1
