### ISSUE TITLE
Can't register Hue bridge to Huemagic

### ISSUE THREAD

**Issue by mathieusibilla** [Foddy/node-red-contrib-huemagic#193]
Hi,

**Describe the bug**
I'm unable to pair my bridge to the node, when oressing the button on the bridge i get the following error in NR:

Error: Cannot find module 'aws4'
Require stack:
- /home/mathieu/.node-red/node_modules/request/request.js
- /home/mathieu/.node-red/node_modules/request/index.js
- /home/mathieu/.node-red/node_modules/node-red-contrib-huemagic/huemagic/hue-bridge-config.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/mathieu/.node-red/node_modules/request/request.js:10:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)

**Please complete the following information:**
 - Node-RED version: v1.1.3
 - NodeJS version: v12.18.3
 - Device running Node-RED: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-112-generic x86_64)

**Additional context**
Ubuntu is running in a VM

**Comment by dongennl** [comment]
hi, looking at the dependencies 'aws4' is required by 'request', which is a dependency of this project. Are you sure your install has been successful? Might be worth uninstalling and re-installing Huemagic.

**Comment by mathieusibilla** [comment]
Hi, thank you for getting back to me.
I have re-install and the bridge has now paired succesfully despite some errors in the log, see below:
2020-08-25T20:15:01.221Z Install : node-red-contrib-huemagic 2.8.6

2020-08-25T20:15:01.246Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-huemagic@2.8.6
2020-08-25T20:15:03.200Z [err] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2020-08-25T20:15:04.313Z [err] npm
2020-08-25T20:15:04.313Z [err]  WARN deprecated har-validator@5.1.5: this library is no longer supported
2020-08-25T20:15:10.405Z [err] npm
2020-08-25T20:15:10.406Z [err]  WARN node-red-project@0.0.1 No repository field.
2020-08-25T20:15:10.423Z [err] npm 
2020-08-25T20:15:10.423Z [err] WARN node-red-project@0.0.1 No license field.
2020-08-25T20:15:10.423Z [err] 
2020-08-25T20:15:10.426Z [out] + node-red-contrib-huemagic@2.8.6
2020-08-25T20:15:10.426Z [out] added 115 packages from 111 contributors in 8.247s
2020-08-25T20:15:10.448Z rc=0

Thanks a lot once more.
Mat
