### ISSUE TITLE
Zone Groups do not work

### ISSUE THREAD

**Issue by bmdevx** [Foddy/node-red-contrib-huemagic#270]
**Describe the bug**
Turning on a group or getting a group status does not work when the group is a 'zone'.

**Flow to Reproduce**
Inject > Group > Debug
UI Button > Debug

**Expected behavior**
When sending a status request, pressing the button in the UI or having the group change via another app, expecting a message to be sent from the node. When sending a message to turn on the lights in the group, expecting the lights to turn on. The button in the UI says '*Zone*: Status queried successfully...'

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/39617180/149042685-8b212a34-aca7-48cf-855c-f30efd2ff7a5.png)
![Screenshot_2](https://user-images.githubusercontent.com/39617180/149042712-b66a146f-7135-4362-8d06-f46966e50957.png)

**Please complete the following information:**
 - Node-RED version: 2.1.4
 - NodeJS version: 14.18.2
 - Device running Node-RED: Intel NUC via docker

Error in NodeRED:
UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'command' on boolean 'false'
    at processImmediate (internal/timers.js:464:21)
    at HueGroup.applyCommands (/data/node_modules/node-red-contrib-huemagic/huemagic/hue-group.js:523:28)
    at HueGroup._inputCallback (/data/node_modules/node-red-contrib-huemagic/huemagic/hue-group.js:95:54)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:204:26
    at HueGroup.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:196:11)
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:149:13)
    at HueGroup.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:180:25)
    at HueGroup.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:479:10)
    at Immediate.<anonymous> (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:814:52)

**Comment by bmdevx** [comment]
After upgrading to 4.0.4 the zone groups seem to be working now. Although I am still getting the error in the NodeRED log.

**Comment by Foddy** [comment]
If you didn’t already, can you please try to restart Node-RED completely and check again if you still see this error in your logs?

**Comment by bmdevx** [comment]
Restarted a few times and am still receiving the error. Although the group node seems to be working. The error is also often following by another message:

(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

**Comment by Foddy** [comment]
@bmdevx thanks for reporting this, and sorry that it took me such an absurd amount of time to get back to you :S

HueMagic still resolved groups over the old API and expected every group to carry a legacy identifier. Newer bridge firmwares stopped handing that out for a lot of rooms and zones, so the lookup came back empty – and you got "The group is not yet available" even though the group itself was perfectly fine. Third party devices behind a group made it worse, because a missing service could send the resolution into recursion.

The whole "Hue Group" node now runs on the CLIP/v2 `grouped_light` service. Rooms, zones and third party devices are found again, `incrementBrightness` / `decrementBrightness` are back, and the group finally reports brightness and colour as well.

This is fixed as of **v5.0.0**, now available on npm.
