### ISSUE TITLE
ReferenceError: err is not defined at EventSource.scope.events.<computed>.onerror

### ISSUE THREAD

**Issue by Darkman1900** [Foddy/node-red-contrib-huemagic#304]
Node-RED crashed with the following logfile output:

Jan 28 23:35:47 homematic-raspi daemon.err node-red: 28 Jan 23:35:47 - ReferenceError: err is not defined
Jan 28 23:35:47 homematic-raspi daemon.err node-red:     at EventSource.scope.events.<computed>.onerror (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/huemagic/utils/api.js:157:102)
Jan 28 23:35:47 homematic-raspi daemon.err node-red:     at EventSource.emit (events.js:315:20)
Jan 28 23:35:47 homematic-raspi daemon.err node-red:     at _emit (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/node_modules/eventsource/lib/eventsource.js:257:17)
Jan 28 23:35:47 homematic-raspi daemon.err node-red:     at onConnectionClosed (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/node_modules/eventsource/lib/eventsource.js:53:5)
Jan 28 23:35:47 homematic-raspi daemon.err node-red:     at IncomingMessage.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/node_modules/eventsource/lib/eventsource.js:170:9)
Jan 28 23:35:47 homematic-raspi daemon.err node-red:     at IncomingMessage.emit (events.js:315:20)
Jan 28 23:35:47 homematic-raspi daemon.err node-red:     at TLSSocket.socketCloseListener (_http_client.js:435:11)
Jan 28 23:35:47 homematic-raspi daemon.err node-red:     at TLSSocket.emit (events.js:327:22)
Jan 28 23:35:47 homematic-raspi daemon.err node-red:     at net.js:673:12
Jan 28 23:35:47 homematic-raspi daemon.err node-red:     at TCP.done (_tls_wrap.js:563:7)
Jan 28 23:35:47 homematic-raspi daemon.err node-red: Node-RED exited with non-zero exit status 1
Jan 28 23:35:47 homematic-raspi daemon.warn redmatic: Restarting Node-RED (1/2)

**Comment by Supergiovane** [comment]
This error occurs on disconnection.
I've created a pull request for that.

**Comment by Foddy** [comment]
@Darkman1900 sorry for the really long silence on this one – it stayed open way longer than it should have :S

@Supergiovane – this hit you as well.

The reason was always the same pattern: HueMagic trusted the bridge's answer a little too much and reached straight into objects that weren't there. One unexpected response and the exception escaped the node – which in Node-RED doesn't just kill the node, it takes the whole instance with it.

All known uncaught exceptions and unhandled promise rejections are closed now. Bridge answers are checked before they are used, a single event that can't be assigned no longer discards the rest of its batch, and timers and listeners are cleaned up properly when a node is removed.

Fixed in **v5.0.0** – the release is on npm 🙂
