### ISSUE TITLE
Err not defined error

### ISSUE THREAD

**Issue by BlaM** [Foddy/node-red-contrib-huemagic#337]
**Describe the bug**
Node red crashed with a "err" not defined message

**Flow to Reproduce**
Don't know, just happened. 

**Expected behavior**
Not crash

**Screenshots**
Mar 18:56:40 - [error] ReferenceError: err is not defined

at EventSource.scope.events.<computed>.onerror (/data/node_modules/node-red-contrib-huemagic/huemagic/utils/api.js:157:102)
at EventSource.emit (events.js:400:28)
at _emit (/data/node_modules/eventsource/lib/eventsource.js:257:17)
at onConnectionClosed (/data/node_modules/eventsource/lib/eventsource.js:53:5)
at IncomingMessage.<anonymous> (/data/node_modules/eventsource/lib/eventsource.js:170:9)
at IncomingMessage.emit (events.js:400:28)
at TLSSocket.socketCloseListener (_http_client.js:441:11)
at TLSSocket.emit (events.js:412:35)
at net.js:686:12
at TCP.done (_tls_wrap.js:564:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@2.2.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1

npm ERR! Failed at the node-red-docker@2.2.2 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /data/.npm/_logs/2022-03-17T17_56_40_954Z-debug.log

**Please complete the following information:**
 - Node-RED version: 2.2.2
 - NodeJS version: [...]
 - Device running Node-RED: unraid

**Comment by BlaM** [comment]
Parameter name in huemagic/util/api.js is error, but variable err is used, so this is an easy fix. I'm not on my computer right now, though.

**Comment by Supergiovane** [comment]
I've already fixed some of these issues, but until the PR isn't merged, no way to fix that. :-)

**Comment by BlaM** [comment]
Duplicate of #304 then
