### ISSUE TITLE
Nodered Crashes Randomly, when i try to start again specific error because of Huemagic

### ISSUE THREAD

**Issue by Danibe1779** [Foddy/node-red-contrib-huemagic#389]
when i try to start nodered again specific errer because of Huemagic 
28 Jul 21:29:46 - [info] [hue-bridge:Philips hue] Connected to bridge
28 Jul 21:29:46 - [red] Uncaught Exception:
28 Jul 21:29:46 - [error] Api Error: Unexpected response status; 404
at requireStatusCode200 (/data/node_modules/node-hue-api/hue-api/httpPromise.js:100:15)
at _fulfilled (/data/node_modules/request-util/node_modules/q/q.js:787:54)
at /data/node_modules/request-util/node_modules/q/q.js:816:30
at Promise.promise.promiseDispatch (/data/node_modules/request-util/node_modules/q/q.js:749:13)
at /data/node_modules/request-util/node_modules/q/q.js:557:44
at flush (/data/node_modules/request-util/node_modules/q/q.js:108:17)
at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by andesse** [comment]
Try my repository 
https://github.com/andesse/hue-clip-api.node-red-flows

**Comment by Danibe1779** [comment]
Well i dont know why but deleting the api folder and restarting nr and everything works as it should , dont know what got corrupted in that folder but basically letting it recreate itself fixed it.
