### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by BreitiDE** [Foddy/node-red-contrib-huemagic#46]
(node:7671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 144)
(node:7671) UnhandledPromiseRejectionWarning: ReferenceError: score is not defined
    at client.sensors.getById.then.catch.error (/home/nodered/.node-red/node_modules/node-red-contrib-huemagic/red/hue-motion.js:105:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

node -v = v8.11.1
node-red = 0.18.4

same problem with node 9.x

**Comment by Foddy** [comment]
Please update HueMagic to 1.5.3. There was a typo in the previous version which caused this error.

**Comment by BreitiDE** [comment]
hi, using 1.5.4 ans still have the problem

(node:31716) UnhandledPromiseRejectionWarning: ReferenceError: score is not defined
    at client.sensors.getById.then.catch.error (/home/nodered/.node-red/node_modules/node-red-contrib-huemagic/red/hue-motion.js:105:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:31716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 204)

now node v9.11.1 with node-red 0.18.4


regards Stefan
