### ISSUE TITLE
Many more ECONNRESET errors with 1.9

### ISSUE THREAD

**Issue by altery** [Foddy/node-red-contrib-huemagic#70]
I upgraded HueMagic from 1.5.x to 1.9. Now I'm getting burst ECONNRESET errors (multiple per second):

```
6 Nov 18:32:38 - [debug] [hue-bridge:Lounge] Error: Huejay: read ECONNRESET
at getHttpClient.request.then.catch.error (/home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
6 Nov 18:32:38 - [debug] [hue-bridge:Lounge] Error: Huejay: read ECONNRESET
at getHttpClient.request.then.catch.error (/home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
6 Nov 18:32:39 - [debug] [hue-bridge:Lounge] Error: Huejay: read ECONNRESET
at getHttpClient.request.then.catch.error (/home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
6 Nov 18:32:39 - [debug] [hue-bridge:Lounge] Error: Huejay: read ECONNRESET
at getHttpClient.request.then.catch.error (/home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
6 Nov 18:32:41 - [debug] [hue-bridge:Lounge] Error: Huejay: read ECONNRESET
at getHttpClient.request.then.catch.error (/home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
6 Nov 18:32:41 - [debug] [hue-bridge:Lounge] Error: Huejay: read ECONNRESET
at getHttpClient.request.then.catch.error (/home/pi/.node-red/node_modules/huejay/lib/Transport.js:106:15)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
```

Some notes:
- The flow only contains 1 universal light and 1 universal group. Both have light id '0' assigned, so 'updates' of light states should be disabled.
- In 1.5.x there were only spare ECONNRESET caused refresh calls of group or light nodes.
- The Hue installation is big: Almost 50 lights are attached.

**Comment by Foddy** [comment]
Did you restarted everything after the update? What’s your installed node-red and node version?

These kind of errors should not be even possible after a clean update to 1.9+, since HueMagic pulls now every device on the bridge with one single request instead of multiple requests per device – and this happens once in your configured interval period which can be min 500ms?

**Comment by altery** [comment]
Yes, I restarted node. Node is 8.12.0 and node-red 0.19.4. I'll try to upgrade to node 10 and node-red 0.19.5

**Comment by altery** [comment]
I cannot upgrade to node 10 due to incompatible third-party dependencies. But I doubt that it would have helped anyway. Upgrading to node-red 0.19.5 did not help. The poll interval ist configured to be 15000ms for that bridge. It seems that a lot of request are sent to the bridge on start of the flow.

**Comment by readeral** [comment]
Is this still an issue?

**Comment by Foddy** [comment]
Changed to sequential request from 2.0+
