### ISSUE TITLE
Crash in recheck loop

### ISSUE THREAD

**Issue by altery** [Foddy/node-red-contrib-huemagic#96]
**Describe the bug**
In my case, huemagic crashes in the recheck loop:

```
11 Sep 17:40:55 - [debug] [hue-bridge:Lounge] TypeError: Cannot read property 'length' of undefined
at HueBridge.getUpdates (/home/pi/.node-red/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:94:25)
at scope.client.rules.getAll.then.then.results (/home/pi/.node-red/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:61:29)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Flow to Reproduce**
Just use the huemagic node with a bridge that has a large number of lights.

**Expected behavior**
It should not crash :)

**Please complete the following information:**
 - NodeRED version: 0.20.8
 - NodeJS version: 8.16.1
 - Device running NodeRED: Pi3B

**Additional context**
I think the problem is an incorrect usage of HueJay promises in hue-brige-config.js: the resources (lights,sensors,groups,rules) are all fetched asynchronously and pushed into an array. when accessing the 'results' array, it is not guaranteed, that the promises have already been executed and the order of resources in the results array is most probably also not deterministic. The promises must be chained to fix the issue, see for example https://javascript.info/promise-chaining

This is the affected code:
```
var results = [];

scope.client.lights.getAll().then(lights => {
	results.push(lights);
	return true;
})
scope.client.sensors.getAll().then(sensors => {
	results.push(sensors);
	return true;
})
scope.client.groups.getAll().then(groups => {
	results.push(groups);
	return true;
})
scope.client.rules.getAll().then(rules => {
	results.push(rules);
	return results;
})
.then(results => {
	let lights = results[0];
	let sensors = results[1];
	let groups = results[2];
	let rules = results[3];

	// GET UPDATES
	let lightUpdates = scope.getUpdates("light", lights);
	let sensorUpdates = scope.getUpdates("sensor", sensors);
	let groupUpdates = scope.getUpdates("group", groups);
	let ruleUpdates = scope.getUpdates("rule", rules);

	// RETURN UPDATES
	return [lightUpdates, sensorUpdates, groupUpdates, ruleUpdates];
})
```

**Comment by altery** [comment]
I adjusted the code accordingly and seems to work now:

```
new Promise(function() {
	return scope.client.lights.getAll();
}).then(lights => {
	results.push(lights);
	return scope.client.sensors.getAll();
}).then(sensors => {
	results.push(sensors);
	return scope.client.groups.getAll();
}).then(groups => {
	results.push(groups);
	return scope.client.rules.getAll();
}).then(rules => {
	results.push(rules);
	return results;
}).then(results => {
	let lights = results[0];
	let sensors = results[1];
	let groups = results[2];
	let rules = results[3];

	// GET UPDATES
	let lightUpdates = scope.getUpdates("light", lights);
	let sensorUpdates = scope.getUpdates("sensor", sensors);
	let groupUpdates = scope.getUpdates("group", groups);
	let ruleUpdates = scope.getUpdates("rule", rules);

	// RETURN UPDATES
	return [lightUpdates, sensorUpdates, groupUpdates, ruleUpdates];
})
(...)
```

**Comment by Foddy** [comment]
Thanks! :)
